#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Sync Camel Spring Boot (Camel 4)

on:
  schedule:
    # Run at midnight every day
    - cron:  '0 0 * * *'
jobs:
  build:
    name: Sync Camel Spring Boot Main Branch
    if: github.repository == 'apache/camel-spring-boot'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Camel project
        uses: actions/checkout@v3
        with:
          repository: apache/camel
          persist-credentials: false
          ref: camel-spring-boot-3.x
          path: camel
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Build Camel Project
        run: ./mvnw -V --no-transfer-progress clean install -DskipTests
        working-directory: ${{ github.workspace }}/camel
      - name: Checkout Camel-spring-boot project
        uses: actions/checkout@v3
        with:
          ref: camel-spring-boot-3.x
          persist-credentials: false
          fetch-depth: 0
      - name: Build Camel-spring-boot Project
        run: ./mvnw -V --no-transfer-progress clean install -DskipTests
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.3
        with:
          base: camel-spring-boot-3.x
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: automatic-periodic-sync
          title: '[Github Actions] Periodic Sync Camel Spring Boot (Camel 3)'
          body: |
            Periodic Sync of Camel Spring Boot Main Branch with main Camel Main.
            see https://github.com/apache/camel-spring-boot/blob/main/.github/workflows/automatic-sync-camel-3.yml
